# Generated by Django 2.1.2 on 2018-11-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0002_company_c_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cominfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('math', models.CharField(max_length=10)),
                ('chinese', models.CharField(max_length=10)),
                ('english', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
