# Generated by Django 2.1.2 on 2018-11-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0003_auto_20181106_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cominfo',
            name='chinese',
        ),
        migrations.RemoveField(
            model_name='cominfo',
            name='english',
        ),
        migrations.RemoveField(
            model_name='cominfo',
            name='math',
        ),
        migrations.AddField(
            model_name='cominfo',
            name='code',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cominfo',
            name='lawperson',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cominfo',
            name='num',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cominfo',
            name='status',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cominfo',
            name='style',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cominfo',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cominfo',
            name='total',
            field=models.CharField(max_length=40),
        ),
    ]
