# Generated by Django 2.1.2 on 2018-12-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
