# Generated by Django 2.1.2 on 2018-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0007_auto_20181218_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
