# Generated by Django 2.1.2 on 2018-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0008_auto_20181218_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
