# Generated by Django 2.1.2 on 2019-01-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0014_auto_20181220_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
