# Generated by Django 2.1.2 on 2019-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comsearch', '0015_auto_20190107_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cominfo',
            old_name='code',
            new_name='credit_code',
        ),
        migrations.RenameField(
            model_name='cominfo',
            old_name='lawperson',
            new_name='organization_code',
        ),
        migrations.RenameField(
            model_name='cominfo',
            old_name='num',
            new_name='registration_num',
        ),
        migrations.RemoveField(
            model_name='cominfo',
            name='total',
        ),
        migrations.AddField(
            model_name='cominfo',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='authority',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='capital',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='e_date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='f_date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='legal_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='term',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cominfo',
            name='trade',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cominfo',
            name='status',
            field=models.CharField(choices=[('存续', '存续'), ('注销', '注销')], default='存续', max_length=40),
        ),
        migrations.AlterField(
            model_name='cominfo',
            name='style',
            field=models.CharField(choices=[('有限责任公司', '有限责任公司'), ('股份有限公司', '股份有限公司'), ('个体工商户', '个体工商户'), ('个人独资企业', '个人独资企业'), ('合伙企业', '合伙企业')], default='有限责任公司', max_length=40),
        ),
    ]
